#include <objc/objc-runtime.h>
#include <Carbon/Carbon.h>
#include <Cocoa/Cocoa.h>
#include <CoreVideo/CoreVideo.h>
#include <mach/mach_time.h>
#include <mach-o/dyld.h>
#include <mach-o/swap.h>
#include <bootstrap.h>

#ifdef __x86_64__
#include <emmintrin.h>
#elif __arm64__
#include <arm_neon.h>
#endif

#include <stdio.h>
#include <stddef.h>
#include <stdlib.h>
#include <stdint.h>
#include <string.h>
#include <dirent.h>
#include <stdbool.h>
#include <assert.h>
#include <fcntl.h>
#include <regex.h>
#include <execinfo.h>
#include <signal.h>
#include <unistd.h>
#include <sys/wait.h>
#include <sys/stat.h>
#include <sys/types.h>
#include <sys/sysctl.h>
#include <sys/socket.h>
#include <sys/un.h>
#include <netinet/in.h>
#include <arpa/inet.h>
#include <netdb.h>
#include <poll.h>
#include <semaphore.h>
#include <pthread.h>
#include <pwd.h>
#include <spawn.h>
#include <libproc.h>

#include "misc/extern.h"
#include "misc/macros.h"
#include "misc/memory_pool.h"
#include "misc/ts.h"
//#include "misc/autorelease.h"
#include "misc/notify.h"
#include "misc/log.h"
#include "misc/helpers.h"
#include "misc/timer.h"
#include "misc/macho_dlsym.h"
#include "misc/sbuffer.h"
#define HASHTABLE_IMPLEMENTATION
#include "misc/hashtable.h"
#undef HASHTABLE_IMPLEMENTATION
#include "misc/service.h"

#include "osax/common.h"

#include "spaces/view.h"
#include "sa/sa.h"
#include "events/event_loop.h"
#include "events/mission_control.h"
#include "events/event_signal.h"
#include "events/workspace.h"
#include "windows/rule.h"
#include "ipc/message.h"
#include "displays/display.h"
#include "spaces/space.h"
#include "windows/window.h"
#include "applications/process_manager.h"
#include "applications/application.h"
#include "displays/display_manager.h"
#include "spaces/space_manager.h"
#include "windows/window_manager.h"
#include "events/mouse_handler.h"

#include "effects/display.h"
#include "effects/window_fade.h"
#include "effects/snapshot.h"
#include "navigation/topology.h"
#include "navigation/admission.h"
#include "navigation/schedule.h"
#include "navigation/step.h"
#include "navigation/activation.h"
#include "navigation/command.h"
#include "hooks.h"

// Navigation and effects come before the core, so they can use only what the
// headers declare.
#include "navigation/admission.c"
#include "navigation/topology.c"
#include "navigation/activation.c"
#include "effects/display.m"
#include "effects/window_fade.c"
#include "effects/snapshot.m"
#include "navigation/step.c"
#include "navigation/schedule.c"
#include "navigation/command.c"

#include "sa/sa.m"
#include "events/mission_control.c"
#include "events/event_queue.c"
#include "events/event_loop.c"
#include "events/event_signal.c"
#include "events/workspace.m"
#include "windows/rule.c"
#include "ipc/message.c"
#include "ipc/commands/config.c"
#include "ipc/commands/display.c"
#include "ipc/commands/space.c"
#include "ipc/commands/window.c"
#include "ipc/commands/query.c"
#include "ipc/commands/rule.c"
#include "ipc/commands/signal.c"
#include "ipc/message_loop.c"
#include "displays/display.c"
#include "spaces/space.c"
#include "spaces/view/feedback.c"
#include "spaces/view/geometry.c"
#include "spaces/view/nodes.c"
#include "spaces/view/direction.c"
#include "spaces/view/operations.c"
#include "spaces/view/lifecycle.c"
#include "windows/window/observation.c"
#include "windows/window/space.c"
#include "windows/window/serialize_nonax.c"
#include "windows/window/serialize.c"
#include "windows/window/attributes.c"
#include "windows/window/properties.c"
#include "windows/window/identity.c"
#include "windows/window/lifecycle.c"
#include "applications/process_manager.c"
#include "applications/application.c"
#include "displays/display_manager.c"
#include "spaces/space_manager/views.c"
#include "spaces/space_manager/labels.c"
#include "spaces/space_manager/layout.c"
#include "spaces/space_manager/selectors.c"
#include "spaces/space_manager/window_moves.c"
#include "spaces/space_manager/operations.c"
#include "spaces/space_manager/state.c"
#include "windows/window_manager/tables.c"
#include "windows/window_manager/query.c"
#include "windows/window_manager/rules.c"
#include "windows/window_manager/frames.c"
#include "windows/window_manager/animation.c"
#include "windows/window_manager/appearance.c"
#include "windows/window_manager/lookup.c"
#include "windows/window_manager/focus.c"
#include "windows/window_manager/operations.c"
#include "windows/window_manager/scratchpad.c"
#include "windows/window_manager/spaces.c"
#include "events/mouse_handler.c"
#include "yabai.c"
